spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgrespend
        username: postgres
        password: taxmap
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update  # Pode ser 'create', 'update', 'validate', ou 'none'
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
