spring:
    datasource:
        url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?user=${DB_USERNAME}.hutqblfdygejxswahakm&password=${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update  # Pode ser 'create', 'update', 'validate', ou 'none'
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQL95Dialect
